'use client';
import { useState, useEffect } from 'react';
import { FileText, TrendingUp, TrendingDown, CheckCircle, AlertTriangle, RefreshCw, Download, Calendar, Zap, Users, DollarSign } from 'lucide-react';

const BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

interface BriefingSection { title: string; items: string[]; }

const MOCK_BRIEFING = {
  generated_at: new Date(Date.now() - 3600000).toISOString(),
  week: 'Week of March 10–16, 2026',
  headline: 'Strong week — 47 tasks completed, 2 high-risk escalations handled, revenue up 34%.',
  kpis: [
    { label: 'Tasks Completed',     value: '47',      delta: '+12%', up: true  },
    { label: 'Emails Processed',    value: '128',     delta: '+8%',  up: true  },
    { label: 'Social Posts',        value: '23',      delta: '+31%', up: true  },
    { label: 'Revenue (PKR)',       value: '185,000', delta: '+34%', up: true  },
    { label: 'Expenses (PKR)',      value: '36,800',  delta: '-5%',  up: false },
    { label: 'Approval Queue',      value: '3',       delta: '-40%', up: false },
  ],
  sections: [
    { title: '✅ Completed This Week', items: [
      'Processed 128 emails — 94 auto-replied, 34 escalated for approval',
      'Posted 23 pieces of social content across LinkedIn, Twitter, Facebook, Instagram',
      'Handled 3 WhatsApp partnership inquiries — 2 forwarded to CEO',
      'Detected and flagged 3 anomalous bank transactions (ROUND_AMOUNT_FLAG)',
      'Generated monthly financial report for February 2026',
      'Renewed LinkedIn OAuth token (was expiring in 48h)',
    ]},
    { title: '⚠️ Escalations & Approvals', items: [
      'HIGH-RISK: Email from ceo@bigcorp.com re: contract renewal ($50k deal) — pending your review',
      'MEDIUM-RISK: LinkedIn post about Q1 results — Claude drafted, awaiting approval',
      'HIGH-RISK: Bank transaction PKR 500,000 to unknown vendor — flagged for investigation',
    ]},
    { title: '📊 Social Performance', items: [
      'LinkedIn: 2,840 followers (+45 this week), avg engagement 4.2%',
      'Twitter: 1,205 followers (+23), 183 tweets total, 2.8% engagement',
      'Instagram: 5,610 followers (+112), 6.7% engagement (best platform)',
      'Facebook: 3,412 followers (+18), 3.1% engagement',
      'Best performing post: "AI transforming SMBs" thread (Twitter, 847 impressions)',
    ]},
    { title: '💰 Financial Summary', items: [
      'Income: PKR 185,000 (Client retainers: 50k, Project work: 25k, Consulting: 100k, Stripe: 37.5k)',
      'Expenses: PKR 36,800 (AWS: 12.8k, Anthropic API: 6k, Contractors: 18k)',
      'Net: PKR 148,200 (+34% vs last week)',
      'Flagged: 2 transactions need review (see Bank Monitor)',
    ]},
    { title: '🔧 System Health', items: [
      'All 11 bots online — uptime 99.8% for the week',
      'Vault: 312 documents indexed, 0 corruption issues',
      'API latency avg: 240ms (within normal range)',
      'Disk usage: 2.3GB / 50GB (4.6%)',
      'Claude API spend this week: $12.40',
    ]},
    { title: '📅 Next Week Priorities', items: [
      'ACTION REQUIRED: Review BigCorp contract renewal (deadline Friday)',
      'Schedule Q2 LinkedIn campaign (3 posts/week strategy)',
      'Follow up with Ali Hassan re: partnership call',
      'Review and approve February financial report',
      'Consider upgrading Twitter plan for higher post limits',
    ]},
  ] as BriefingSection[],
};

export default function ReportPage() {
  const [briefing] = useState(MOCK_BRIEFING);
  const [generating, setGenerating] = useState(false);
  const [activeSection, setActiveSection] = useState<number|null>(null);

  const generate = async () => {
    setGenerating(true);
    try { await fetch(`${BASE}/api/briefing/generate`, { method: 'POST' }); } catch { /* ignore */ }
    setTimeout(() => setGenerating(false), 2000);
  };

  return (
    <div className="animate-fade-in max-w-4xl space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold" style={{color:'#f1f5f9'}}>CEO Weekly Briefing</h1>
          <p className="text-sm" style={{color:'#64748b'}}>Auto-generated by Claude every Sunday · {briefing.week}</p>
        </div>
        <div className="flex gap-2">
          <button onClick={generate} disabled={generating}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm"
            style={{background:'#1e2035',color:'#94a3b8',border:'1px solid #2a2d45'}}>
            {generating ? <RefreshCw size={14} className="animate-spin"/> : <Zap size={14}/>}
            Generate Now
          </button>
          <button className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm"
            style={{background:'#1e2035',color:'#94a3b8',border:'1px solid #2a2d45'}}>
            <Download size={14}/> Export
          </button>
        </div>
      </div>

      {/* Headline */}
      <div className="rounded-xl p-5" style={{background:'linear-gradient(135deg,rgba(59,130,246,0.1),rgba(124,58,237,0.1))',border:'1px solid rgba(59,130,246,0.2)'}}>
        <div className="flex items-start gap-3">
          <FileText size={20} style={{color:'#60a5fa',flexShrink:0,marginTop:2}}/>
          <div>
            <div className="text-xs font-semibold mb-1" style={{color:'#475569'}}>
              <Calendar size={11} className="inline mr-1"/>{briefing.week} · Generated {new Date(briefing.generated_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
            </div>
            <p className="text-sm leading-relaxed" style={{color:'#e2e8f0'}}>{briefing.headline}</p>
          </div>
        </div>
      </div>

      {/* KPI grid */}
      <div className="grid grid-cols-2 lg:grid-cols-3 gap-3">
        {briefing.kpis.map(kpi => (
          <div key={kpi.label} className="rounded-xl p-4" style={{background:'#0f1020',border:'1px solid #1e2035'}}>
            <div className="text-xs mb-2" style={{color:'#64748b'}}>{kpi.label}</div>
            <div className="flex items-end justify-between">
              <div className="text-xl font-bold" style={{color:'#f1f5f9'}}>{kpi.value}</div>
              <div className="flex items-center gap-1 text-xs font-semibold"
                style={{color:kpi.up?'#34d399':'#f87171'}}>
                {kpi.up ? <TrendingUp size={12}/> : <TrendingDown size={12}/>}
                {kpi.delta}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Briefing sections */}
      <div className="space-y-3">
        {briefing.sections.map((section, i) => (
          <div key={i} className="rounded-xl overflow-hidden" style={{background:'#0f1020',border:'1px solid #1e2035'}}>
            <button onClick={() => setActiveSection(activeSection===i ? null : i)}
              className="w-full flex items-center justify-between px-5 py-3 text-left hover:bg-[#13141f] transition-colors">
              <span className="text-sm font-semibold" style={{color:'#e2e8f0'}}>{section.title}</span>
              <span className="text-xs px-2 py-0.5 rounded-full" style={{background:'rgba(59,130,246,0.1)',color:'#60a5fa'}}>
                {section.items.length} items
              </span>
            </button>
            {(activeSection===i || activeSection===null) && (
              <ul className="px-5 pb-4 space-y-2">
                {section.items.map((item, j) => (
                  <li key={j} className="flex items-start gap-2 text-sm" style={{color:'#94a3b8'}}>
                    <span className="w-1 h-1 rounded-full mt-2 flex-shrink-0" style={{background:'#3b82f6'}}/>
                    {item}
                  </li>
                ))}
              </ul>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
